// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8NB23FIJsjcTkqPWjTX6Ek_QcXr6TS0',
    appId: '1:967464933907:web:8bc2a0ad0ef889f5203de6',
    messagingSenderId: '967464933907',
    projectId: 'inclass-14-1b3ca',
    authDomain: 'inclass-14-1b3ca.firebaseapp.com',
    storageBucket: 'inclass-14-1b3ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw-DMMPnBrpgcMhRmcy7a_hItkfaaxnPM',
    appId: '1:967464933907:android:efe7619e43f40b55203de6',
    messagingSenderId: '967464933907',
    projectId: 'inclass-14-1b3ca',
    storageBucket: 'inclass-14-1b3ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA1DLUY6JE5hcIskvHCV1SOB0QRnDKuzA',
    appId: '1:967464933907:ios:829e0cf7a7df6b4f203de6',
    messagingSenderId: '967464933907',
    projectId: 'inclass-14-1b3ca',
    storageBucket: 'inclass-14-1b3ca.firebasestorage.app',
    iosBundleId: 'com.example.inclass14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA1DLUY6JE5hcIskvHCV1SOB0QRnDKuzA',
    appId: '1:967464933907:ios:829e0cf7a7df6b4f203de6',
    messagingSenderId: '967464933907',
    projectId: 'inclass-14-1b3ca',
    storageBucket: 'inclass-14-1b3ca.firebasestorage.app',
    iosBundleId: 'com.example.inclass14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr8NB23FIJsjcTkqPWjTX6Ek_QcXr6TS0',
    appId: '1:967464933907:web:050320a0b144422d203de6',
    messagingSenderId: '967464933907',
    projectId: 'inclass-14-1b3ca',
    authDomain: 'inclass-14-1b3ca.firebaseapp.com',
    storageBucket: 'inclass-14-1b3ca.firebasestorage.app',
  );
}
